miyuchina/mistletoe

contrib/Makefile
contrib/md2jira.py
makefile
plugins/jira_renderer.py
test/test_plugins/test_jira_renderer.py

This PR includes support for rendering JIRA wiki markup as specified in <https://jira.atlassian.com/secure/WikiRendererHelpAction.jspa?section=all>
An additional script `md2jira.py` will convert a Markdown (CommonMark) formatted file to JIRA wiki and can be installed in the `bin` directory of the user's home.

Initial support for JIRA wiki rendering

---

contrib/md2jira.py

This fixes the import because currently, `jira_renderer.py` is in `/contrib` and there is no `/plugins` directory.

Fix for tiny import bug

---

contrib/jira_renderer.py

The newline at this point is unnecessary and for example, it creates a line break at the beginning of each document that begins with a headline.

Headline fix

---

mistletoe/block_tokenizer.py

This PR fix #58: see that issue for the rationale.

Fix FileWrapper backstep after StopIteration

---

mistletoe/base_renderer.py

Currently you subclass a token and then subclass that token…
For example:
```python
class Foo(SpanToken):
pass
class Bar(Foo):
pattern = re.compile('(@@@)')
class BarRenderer(HTMLRenderer):
def __init__(self):
super().__init__(Bar)
mistletoe.markdown('', BarRenderer)
```
gives the following error:
```
Traceback (most recent call last):
File "bug.py", line 21, in <module>
mistletoe.markdown('', BarRenderer)
File "/path/to/mistletoe/lib/python3.7/site-packages/mistletoe/__init__.py", line 18, in markdown
with renderer() as renderer:
File "bug.py", line 18, in __init__
super().__init__(Bar)
File "/path/to/mistletoe/lib/python3.7/site-packages/mistletoe/html_renderer.py", line 30, in __init__
super().__init__(*chain((HTMLBlock, HTMLSpan), extras))
File …
```

Allow more than one level of token subclass

---

mistletoe/block_token.py

This pull request fixes the issue mentioned in #65.
Markdown:
```markdown
* Foo
1. Bar
```
Before:
```html
<ul>
<li>
<p>Foo</p>
<li>
</ul>
<ol>
<li>Bar</li>
</ol>
```
After:
```html
<ul>
<li>Foo<li>
</ul>
<ol>
<li>Bar</li>
</ol>
```

Fixed incorrect loose list (#65)

---

mistletoe/block_token.py
test/test_block_token.py

Tables with incomplete rows currently crash the parser. For example this Markdown
```
|t1 | t2|
|---|---|
|c1|
```
Note the missing second column in the last row.
```
In [1]: import mistletoe
In [2]: mistletoe.__version__
Out[2]: '0.7.1'
In [6]: mistletoe.markdown("""|t1|t2|
...: |---|---|
...: |c1|""")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-c65559176709> in <module>()
1 mistletoe.markdown("""|t1|t2|
2 |---|---|
----> 3 |c1|""")
.../site-packages/mistletoe/__init__.py in markdown(iterable, renderer)
17     """
18     with renderer() as renderer:
---> 19         return renderer.render(Document(iterable))
.../site-packages/mistletoe/block_token.py in …
```

Tables can handle rows with missing columns

---

mistletoe/latex_renderer.py

In particular the end of line marker \\ was, incorrectly, not added at the end of each row. Now it is.

Fixed problem in latex table rendering

---

.gitignore
contrib/jira_renderer.py
mistletoe/cli.py
test/base_test.py
test/samples/basic_blocks.jira
test/samples/basic_blocks.md
test/samples/lists.jira
test/samples/lists.md
test/samples/quotes.jira
test/samples/quotes.md
test/test_cli.py
test/test_contrib/test_jira_renderer.py

Like #97, this mainly **removes empty lines within lists** for their proper Jira rendering.
It also **fixes other JIRARenderer problems**, so that the renderer is basically usable for real-world scenarios. In short, the main fixes (see individual commits for more details):
* Properly separate paragraphs and others by an empty line.
* Line as well as block quotes are generated.
* Don't HTML-escape all the text. (or please explain why to do it)
* The intended outputs are covered by unit tests which can be easily extended by following a simple naming convention.
Note that I'm rather a Python newbie, so don't hesitate to correct me to possibly better follow the Python-style coding.

JIRARenderer: Fix empty lines between block elements and more

---

contrib/jira_renderer.py
test/test_contrib/test_jira_renderer.py

A small fix; without it the first (header) row was replaced with the second row.

Fix jira_renderer to correctly output table headers; add a test.

---

contrib/jira_renderer.py

```
|    Table    | Non_unique |  Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Visible | Expression |
|-------------|------------|-----------|--------------|-------------|-----------|-------------|----------|--------|------|------------|---------|---------------|---------|------------|
| page_config |     0      |  PRIMARY  |      1       |      id     |     A     |      27     |   None   |  None  |      |   BTREE    |         |               |   YES   |    None    |
| page_config |     0      | UNIQ_USER |      1       |   user_id   |     A     |      27     |   None   |  None  |      |   BTREE    |         |               |   YES   |    None    |
```
after jira_render, got
``` …
```

Update jira_renderer.py - Fix rendering of empty table cells

---

mistletoe/block_token.py
mistletoe/span_token.py
mistletoe/token.py
test/test_repr.py

This pull request adds a `__repr__` method to all token classes. To simplify implementation it introduces a common base class `token.Token` for `block_token.BlockToken` and `span_taken.SpanToken`. For the following example program:
```python
from mistletoe import block_token, span_token, utils
d = block_token.Document(open("test/samples/quotes.md", "r").read())
print([tr.node for tr in utils.traverse(d)])
```
The output looks like this without `__repr__` methods:
```
[<mistletoe.block_token.Heading at 0x10fa5aec0>,
<mistletoe.block_token.Quote at 0x10f99e2c0>,
<mistletoe.block_token.Paragraph at 0x10fb95a50>,
<mistletoe.block_token.Quote at 0x10fb94130>,
<mistletoe.block_token.Paragraph at 0x10fb97970>,
<mistletoe.block_token.Quote at 0x10fb94c10>,
<mistletoe.block_token.Paragraph at …
```

Add __repr__ methods to all token classes

---

contrib/jira_renderer.py
contrib/md2jira.py
contrib/scheme.py
contrib/toc_renderer.py
contrib/xwiki20_renderer.py
mistletoe/__init__.py
mistletoe/base_renderer.py
mistletoe/block_token.py
mistletoe/html_renderer.py
test/test_block_token.py
test/test_contrib/test_jira_renderer.py
test/test_contrib/test_toc_renderer.py
test/test_contrib/test_xwiki20_renderer.py
test/test_core_tokens.py
test/test_latex_renderer.py
test/test_repr.py
test/test_span_token.py

Removing all unused stuff identified by running:
autoflake --remove-all-unused-imports --remove-unused-variables -r -i .

refactor: remove unused imports and variables (#146)

---

CONTRIBUTING.md

The dev branch hasn't been updated in more than 3 years. Thus, the
recommendation to "check...the dev branch regularly" because "the
master branch is updated only when features on the dev branch are
stabilized" is misleading.

Remove reference to dev branch in CONTRIBUTING.md

---

mistletoe/latex_renderer.py
test/test_latex_renderer.py

The LaTeX renderer uses `\verb` for inline code, but the delimiter is
always a vertical bar, which produces incorrect output when the inline
code also contains a vertical bar (e.g., `example | pipe`).
Rather than using a single static character (i.e., a vertical bar),
this change modifies render_inline_code to search for a non-letter
delimiter that does not appear in the inline code. If no such
delimiter can be found, a RuntimeError is raised to avoid incorrect
output.
Note that the list of possible delimiters is not exhaustive. For
example, numbers (0, 1, 2, etc.) are all valid delimiters for \verb
but are omitted from the search.
Fixes #149

Ensure LaTeX renderer uses valid \verb delimiter

---

mistletoe/block_token.py
mistletoe/span_token.py

Improved some docstrings:
- mapping between mistletoe and commonmark terminology,
- describing the representation of the content of the tokens.

Improved some docstrings

---

test/test_contrib/test_github_wiki.py

Hi, here's a fix for issue #142. The problem was that the `GithubWiki` token didn't get added to `span_token._token_types` as intended under pytest.

Bug fix for #142: pytest failing.

---

mistletoe/utils.py
test/test_traverse.py

The `traverse()` utility function was previously written to filter
children by class using `issubclass(child, klass):`. But the first
argument to `issubclass()` must be a class so this will always raise an
exception when trying to use the functionality. This patch corrects the
call to `isinstance(child, klass)` and adds a test.

fix: Make filtering children by class in traverse() actually work

---

mistletoe/utils.py
test/test_traverse.py

Previously, any class filter given to `traverse` wouldn't be respected
for the source node (returned if `include_source=True`). This patch
addresses this.
This is considered a bug fix as opposed to a breaking change because:
* Filtering by class was broken anyway in the last mistletoe release.
* It is unintuitive and likely unintended for the filter not to apply to
the source node.

fix: Apply traverse class filter to source when include_source=True

---

mistletoe/utils.py
test/test_traverse.py

Due to a typo (inverted comparison), the test for the traversal depth would always fail. Fix that typo and add test coverage.

fix: Make limiting depth in traverse() actually work

---

mistletoe/html_renderer.py
mistletoe/span_token.py
test/specification/spec.sh
test/test_html_renderer.py
test/test_span_token.py

This PR fixes nine of the failing examples in the CommonMark 0.30 specification. They all had in common that content inside code spans was not handled according to the spec.
This was solved by preserving space and escape sequences during parsing, and by removing leading and trailing space according to the spec during HTML rendering.
The PR also includes a fix for a warning, a simplified way to download the spec tests examples, and an improvement to the spec test runner.

Fix for part of #108, Update to CommonMark v0.30

---

mistletoe/block_token.py
test/test_block_token.py

Also fixes failing test case 201 in the CommonMark 0.30 test suite.
The fix was done in two steps. Please see commit messages for more details.

Fix for #132, Blocks in between footlink definitions are skipped when parsing

---

contrib/jira_renderer.py
test/test_contrib/test_jira_renderer.py

Sample _Markdown_:
```md
Sample: [inner](https://target "title")
```
In _Linux_, test with:
```sh
mistletoe -r contrib.jira_renderer.JIRARenderer <(echo 'Sample: [inner](https://target "title")')
```
_Jira_ result, before this PR changes:
```
Sample: [inner|https://target]
```
_Jira_ result, after this PR changes:
```
Sample: [inner|https://target|title]
```

💡 implement link titles in the JIRARenderer (contrib)

---

mistletoe/block_token.py
test/test_block_token.py

Also fixes failing examples 312 and 313 in the CommonMark 0.30 spec, due to the way leading space
is now checked for list items.
The direct cause of the reported bug was that only spaces and not tabs were considered
valid separators for list item markers. Another problem was that the implemented tab expansion,
where tabs were always expanded to four spaces, did not work according to the spec, which states
that tabs should be expanded to the nearest tab stop (of width 4).
This fix uses `expandtabs()` to implement the tab stops correctly and moves extraction
of content into the `parse_marker()` and `parse_continuation()` methods. This lets
us implement use cases like "list interrupts a paragraph" and "list item continuation"
in a less error-prone way.

Fix for #89, List Items separated by tab character not parsed correctly.

---

mistletoe/block_token.py
mistletoe/core_tokens.py
mistletoe/html_renderer.py
mistletoe/span_token.py
mistletoe/span_tokenizer.py
test/test_block_token.py
test/test_span_token.py

A set of small fixes which improve the CommonMark spec compliance. See the commit messages for details.

Fix for #108, CommonMark 0.30 spec compliance, part 2

---

mistletoe/block_token.py
mistletoe/span_token.py
mistletoe/token.py
test/test_contrib/test_github_wiki.py

This is a proposed refactoring to clean up the state management during parsing a tiny little bit. Instead of having separate _root_node references in the block_token and span_token modules, we merge the two into one and move it to a module already referenced by both of them: token.py.

Merge block_token._root_node and span_token._root_node into a single object

---

mistletoe/ast_renderer.py
mistletoe/token.py
test/test_ast_renderer.py
test/test_repr.py

This is an attempt to make the two places in the code base where metadata is handled -- the ASTRenderer and Token.repr -- work in a similar way, and most importantly: to display only selected attributes on the tokens (as specified in repr_attributes), instead of displaying everything it can find. The PR also includes a small bug fix for Token.repr.
This PR was split out from #169.
In more detail:
* Updated the AST renderer to display the "official" attributes on the tokens (as specified in repr_attributes), instead of grabbing all attributes it can find.
* Added footnotes to the repr_attributes on the Document token. This is the only attribute expected by the ASTRenderer test suite which wasn't already listed in repr_attributes.
* Bug fix for Token.repr: only instance attributes should be …

Improvements to metadata handling

---

mistletoe/block_token.py
mistletoe/contrib/pygments_renderer.py
mistletoe/html_renderer.py
test/test_block_token.py
test/test_repr.py

Modified the HTMLBlock to store its content in a RawText child node, like all the other block tokens, instead of a content attribute.  This makes it easier to iterate over the token tree, because all block tokens can be handled the same way.
Added a convenience wrapper to preserve backward compatibility.

Modified the HTMLBlock token as described in #163, Inconsistencies in the block tokens

---

README.md
dev-guide.md
mistletoe/block_token.py
mistletoe/core_tokens.py
mistletoe/markdown_renderer.py
mistletoe/span_token.py
test/test_block_token.py
test/test_markdown_renderer.py
test/test_repr.py
test/test_span_token.py

This is a pull request for a Markdown-to-Markdown renderer (#4).
A few notes on the implementation:
1. Since the aim is to preserve as much of the formatting as possible, and also steer clear of issues like if
the sequence `_**Hello**_` would be rendered as `***Hello***` (which changes its interpretation),
I had to save some formatting information from the parsing in the tokens. The formatting info will not appear in the output from the ASTRenderer or from repr().
2. The Markdown renderer can also do word wrapping. (Because I needed that for a use case.) But that's optional, and when it's not enabled, the goal is still to make the roundtrip Markdown -> parse -> render -> Markdown with as few changes as possible.
3. The test cases in `TestMarkdownRenderer` give a pretty good idea of what …

Markdown renderer

---

.github/workflows/python-package.yml
mistletoe/base_renderer.py
mistletoe/contrib/github_wiki.py
mistletoe/contrib/mathjax.py
mistletoe/contrib/toc_renderer.py
mistletoe/html_renderer.py
mistletoe/latex_renderer.py
test/specification/commonmark.py
test/test_html_renderer.py

Introduce additional parameters for the `HTMLRenderer` constructor that control double and single quotes escaping.
Also revert to previous behavior when single quotes are not escaped (by default).

feat: optional html quotes escaping for HTMLRenderer (#176)

---

.github/workflows/python-package.yml
mistletoe/contrib/pygments_renderer.py
test/test_contrib/test_pygments_renderer.py

this fixes an error when an unknown language is encountered in the PygmentsRenderer

fixing "pygments.util.ClassNotFound: no lexer for alias" error

---

test/test_ast_renderer.py
test/test_contrib/test_jira_renderer.py
test/test_contrib/test_pygments_renderer.py
test/test_contrib/test_xwiki20_renderer.py
test/test_html_renderer.py
test/test_latex_renderer.py
test/test_markdown_renderer.py

It's easy and unified now (with no exceptions, right?! :)):
1. As per unittest's documentation examples, `actual` always goes before `expected`.
2. If used, `actual` is stored in a variable `output` for us.
3. If used, variable `expected` is defined after the `output` variable.
For curious ones, Python (as well as the rest of the world) is not consistent here: https://stackoverflow.com/questions/40945126/parameter-order-for-unittest-testcase-assertequal.

test: unify assertEqual calls in all the tests

---

mistletoe/block_token.py
mistletoe/block_tokenizer.py
test/test_block_token.py

Issue found during implementation of #166, when checking for the start of `Table` tokens.
When checking if a table starts on a line, one needs to scan multiple lines without consuming any content. The way to do this is with the anchor/reset methods on the `FileWrapper` class. However, this breaks the parsing of `List` tokens, because these also use anchor/reset, and the anchor set by `List` gets overwritten by the one set in `Table`.
The proposed solution is to not store the anchor position on the `FileWrapper`, but instead move that responsibility to the parsing method. This way, recursive parsing can hold multiple anchors at the same time, without any interference.

Changed FileWrapper anchor/reset to getpos/setpos.

---

mistletoe/block_token.py
test/test_block_token.py

This PR introduces a more modular way to detect when a block token interrupts a paragraph. It also makes `Table` tokens interrupt paragraphs, using the new mechanism.
Adding it as a draft PR for now, due to the dependency on #186 .
In addition to the "obvious" use in `Paragraph.read()`, checks for paragraph interruptions are also done in `Quote.read()` and `ListItem.read()` to determine whether a line is a lazy continuation line or not.
Using the new mechanism to check for continuation lines in `Quote` and `ListItem` does change the parsing behavior, and I believe it's for the better. The old implementation of these checks did not include `HTMLBlock`, for example. There are no test cases in the CommonMark test suite to prove it, but I believe the new implementation is closer to the …

Make tables interrupt paragraphs (#166)

---

mistletoe/latex_renderer.py
test/test_latex_renderer.py

If `\url{}` is used within macros like `\multicolumn` and if the link to
be rendered contains `#` or `%` as typical confluence links like
https://site.com/confluence/display/TEST/TEST-042%3A+Foo#target
are bound to, pdflatex (from TeX Live 2019) fails with errors. This
patch fixes that by escaping these two characters.
NB: if `\url{}` with such links is used outside of multicolumn-macros,
they work regardless of whether these characters are escaped, and the
result remains the same.

Escape special LaTeX characters in URLs

---

README.md
dev-guide.md
docs/__init__.py
docs/index.html
mistletoe/__init__.py
mistletoe/ast_renderer.py
mistletoe/block_token.py
mistletoe/cli.py
mistletoe/contrib/github_wiki.py
mistletoe/contrib/jira_renderer.py
mistletoe/contrib/mathjax.py
mistletoe/contrib/md2jira.py
mistletoe/contrib/pygments_renderer.py
mistletoe/contrib/toc_renderer.py
mistletoe/contrib/xwiki20_renderer.py
mistletoe/html_renderer.py
mistletoe/markdown_renderer.py
mistletoe/span_token.py
test/specification/commonmark.py
test/test_ast_renderer.py
test/test_block_token.py
test/test_cli.py
test/test_contrib/test_jira_renderer.py
test/test_contrib/test_toc_renderer.py
test/test_html_renderer.py
test/test_repr.py
test/test_span_token.py

Fixes #182.
Giving this as a preview of the changes for a while, provided someone would like to give feedback.
Note that backwards compatibility is preserved - by introducing aliases for the old class names.

refactor: use strict PascalCase for class names (#182)

---

mistletoe/markdown_renderer.py
test/test_markdown_renderer.py

When using the Markdown renderer, if a fragment containing newline characters is encountered, it is split by `\n` and each line is yielded in turn.
```py
for fragment in fragments:
if "\n" in fragment.text:
lines = fragment.text.split("\n")
yield current_line + lines[0]
for inner_line in lines[1:-2]:
yield inner_line
current_line = lines[-1]
else:
current_line += fragment.text
```
However, with a quick check in the python REPL we find:
```py
>>> "abcde"[0] 
'a'
>>> "abcde"[1:-2]
'bc'
>>> "abcde"[-1]
'e'
```
Notably, `d`, the penultimate element, is being skipped. 
This can be fixed by changing the bounds of the 'inner' slice from `[1:-2]` to `[1:-1]`.

Fix penultimate sections of multiline fragments being ignored by the Markdown renderer

---

mistletoe/block_token.py
mistletoe/markdown_renderer.py
test/test_markdown_renderer.py
test/test_repr.py

With only `ListItem.prepend`, it is not able to keep original indentation of the 1st line in a list item (#196),
so I add the `indentation` to `ListItem` as its member.
The `indentation` is the indentation from the margin.
I also add it to `repr_attributes` because `prepend` is there too.
After recording indentation, Markdown renderer can restore the indentation from the list marker and from the margin.
I weigh the trade-off between thoroughly retaining the format and consistency of formatting feature.
Therefore, Markdown renderer does not restore the indentation from the margin.
input markdown:
```
indentation from the margin
-   The list item is indented by 1 spaces.
indentation from the list marker
-   The list marker is followed by 3 spaces.
```
implementation details of the 2 …

feat: record indentation on list item to make Markdown renderer be able to render list markers followed by 1~4 spaces.

---

dev-guide.md
mistletoe/block_token.py
mistletoe/block_tokenizer.py
mistletoe/markdown_renderer.py
test/samples/line_numbers.md
test/test_ast_renderer.py
test/test_block_token.py
test/test_line_numbers.py
test/test_repr.py

This is a partial solution for #144 which records line numbers on all _block_ tokens. The _span_ tokens are still left unlabeled, but at least it's a starting point, and I think the functionality added here is useful by itself.
Open question: should the `line_number` be a added to `repr_attributes`, so that it gets included in the output from `ASTRenderer`?

Add line numbers on all block tokens during parsing (#144)

---

mistletoe/markdown_renderer.py
test/test_markdown_renderer.py

This follows #197 and adds the possibility to switch ON the original renderer behavior when the space after list marker (called leader in mistletoe) collapsed just to 1 space.

feat(markdown-renderer): option to normalize spacing after the list marker

---

mistletoe/block_token.py
test/test_block_token.py

feat: allow just 1 dash in Table delimiter cells (#131)

---

mistletoe/html_renderer.py
test/test_html_renderer.py

feat(html-renderer): option to skip HTML tokens parsing (#74)

---

mistletoe/contrib/mathjax.py
test/test_contrib/test_mathjax.py

previously it was converting mathjax unsupported inline math delimiters $ to block math delimiters $$ which are not equivalent. here it instead converts inline math delim $ to the mathjax supported inline math delim \\( \\) which have the expected equivalent behavior

fix inline mathjax handling

---

dev-guide.md
mistletoe/ast_renderer.py
mistletoe/html_renderer.py
mistletoe/span_token.py
mistletoe/token.py
mistletoe/utils.py
test/test_block_token.py
test/test_span_token.py

This resolves #71 and is a continuation / replacement for PR #72.

feat: add parent attribute (#71)

---

mistletoe/markdown_renderer.py
test/test_markdown_renderer.py

The extra spacing can be before of after leader, so try to preserve it on both positions.
Fixes #213

fix(markdown-renderer): preserve list margin spacing

---

.github/workflows/python-package.yml
test-requirements.txt
tox.ini

Define all the needed requirements and the
test command, so that running `tox` runs the
unit tests and runs them successfully.
Also simplify the CI workflow by using both
requirements files - exactly how tox does it.
Fixes #220 and #221.

build: add proper configuration for tox/tests

---

setup.py

Hi! Mistletoe has type hints, but sadly they aren't available when you're using it as a library unless you include py.typed file (for example see https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package )
I checked the change locally: before the change running mypy on my project would result in this
```
src/promnesia/sources/markdown.py:7:1:7:1: error: Skipping analyzing "mistletoe": module is installed, but missing library stubs or py.typed marker  [import-untyped]
import mistletoe
^
src/promnesia/sources/markdown.py:8:1:8:1: error: Skipping analyzing "mistletoe.span_token": module is installed, but missing library stubs or py.typed marker  [import-untyped]
from mistletoe.span_token import AutoLink, Link
^
```
After the change that works! And now it's catching …

include py.typed file to make typing annotations available for library users

---

mistletoe/latex_renderer.py
test/test_latex_renderer.py

Given the following markdown snippet
```md
line
---
other line
```
and creating a pdf from the rendered LaTeX with pdflatex, version pdfTeX 3.141592653-2.6-1.40.25 (TeX Live 2023/Debian)), I get
However, I'd expect the horizontal rule to be on a separate line as shown in the following image
The attached patch fixes that by adding an empty line before the `\hrulefill`.
To reproduce, run the following script and create a pdf from the resulting LaTeX-file via `pdflatex test.tex`:
```python
#!/bin/env python3
import mistletoe
from mistletoe.latex_renderer import LaTeXRenderer
def render(f):
with open(f, 'r') as fp:
return mistletoe.markdown(fp, LaTeXRenderer)
test = """
line
---
other line
"""
open('test.md', 'w').write(test)
open('test.tex', 'w').write(render('test.md'))
```

fix(latex-renderer): thematic break on new line
